/**
 * LinkHub New Tab - 本地 Favicon 映射
 * 使用 data:image/svg+xml;utf8 格式，避免网络请求
 */

const FAVICON_MAP = {
  // AI & ML
  'https://chat.openai.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2310a37f"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">C</text></svg>`,
  'https://claude.ai': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23cc785c"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">C</text></svg>`,
  'https://gemini.google.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%234285f4"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">G</text></svg>`,
  'https://perplexity.ai': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2320b9d4"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">P</text></svg>`,
  'https://deepseek.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232d2d2d"/><text x="16" y="22" font-size="16" font-weight="bold" fill="%2360a5fa" text-anchor="middle" font-family="system-ui">D</text></svg>`,
  'https://kimi.moonshot.cn': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%237c3aed"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">K</text></svg>`,
  'https://tongyi.aliyun.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff6a00"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">T</text></svg>`,
  'https://yiyan.baidu.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232932e1"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">B</text></svg>`,
  'https://huggingface.co': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ffd21e"/><text x="16" y="22" font-size="16" font-weight="bold" fill="%23a36200" text-anchor="middle" font-family="system-ui">H</text></svg>`,
  'https://tensorflow.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff6f00"/><text x="16" y="22" font-size="16" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">T</text></svg>`,

  // 前端开发
  'https://vuejs.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2342b883"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">V</text></svg>`,
  'https://react.dev': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2361dafb"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%2320232a" text-anchor="middle" font-family="system-ui">R</text></svg>`,
  'https://angular.io': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23dd0031"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">A</text></svg>`,
  'https://tailwindcss.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2338bdf8"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">T</text></svg>`,
  'https://element-plus.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23409eff"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">E</text></svg>`,
  'https://ant.design': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%231677ff"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">A</text></svg>`,
  'https://getbootstrap.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%237952b3"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">B</text></svg>`,
  'https://developer.mozilla.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="10" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">MDN</text></svg>`,
  'https://caniuse.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%233b8dca"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">?</text></svg>`,
  'https://www.typescriptlang.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%233178c6"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">TS</text></svg>`,

  // 后端开发
  'https://nodejs.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23339933"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">N</text></svg>`,
  'https://python.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%233776ab"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">Py</text></svg>`,
  'https://spring.io': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%236db33f"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">S</text></svg>`,
  'https://go.dev': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2300add8"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">Go</text></svg>`,
  'https://www.rust-lang.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%23dea584" text-anchor="middle" font-family="system-ui">R</text></svg>`,
  'https://dotnet.microsoft.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23512bd4"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">.N</text></svg>`,
  'https://expressjs.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%2368a063" text-anchor="middle" font-family="system-ui">E</text></svg>`,
  'https://fastapi.tiangolo.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23009688"/><text x="16" y="22" font-size="12" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">Fast</text></svg>`,
  'https://www.djangoproject.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23092e20"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%234eb870" text-anchor="middle" font-family="system-ui">D</text></svg>`,
  'https://flask.palletsprojects.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%23fff" text-anchor="middle" font-family="system-ui">Fl</text></svg>`,

  // DevOps & 云服务
  'https://docker.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232496ed"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">D</text></svg>`,
  'https://kubernetes.io': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23326ce5"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">K</text></svg>`,
  'https://github.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23181717"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">GH</text></svg>`,
  'https://gitlab.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23fc6d26"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">GL</text></svg>`,
  'https://gitee.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23c71d23"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">G</text></svg>`,
  'https://aws.amazon.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff9900"/><text x="16" y="22" font-size="12" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">AWS</text></svg>`,
  'https://aliyun.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff6a00"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">A</text></svg>`,
  'https://vercel.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">V</text></svg>`,
  'https://netlify.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2300c7b7"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">N</text></svg>`,
  'https://nginx.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23009639"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">NG</text></svg>`,

  // 开发工具
  'https://code.visualstudio.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23007acc"/><text x="16" y="22" font-size="12" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">VS</text></svg>`,
  'https://jetbrains.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%23fc801d" text-anchor="middle" font-family="system-ui">JB</text></svg>`,
  'https://postman.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff6c37"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">P</text></svg>`,
  'https://insomnia.rest': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%235841d8"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">I</text></svg>`,
  'https://tableplus.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%231a73e8"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">T+</text></svg>`,
  'https://dbeaver.io': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%233f47a9"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">DB</text></svg>`,
  'https://figma.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23f24e1e"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">F</text></svg>`,
  'https://notion.so': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23fff"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%23000" text-anchor="middle" font-family="system-ui">N</text></svg>`,
  'https://obsidian.md': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%237c3aed"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">O</text></svg>`,
  'https://github.com/features/copilot': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23181717"/><text x="16" y="22" font-size="12" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">GH</text></svg>`,

  // 社区 & 问答
  'https://stackoverflow.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23f48024"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">SO</text></svg>`,
  'https://segmentfault.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%230999ca"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">SF</text></svg>`,
  'https://juejin.cn': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23007fff"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">掘</text></svg>`,
  'https://csdn.net': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23c9151e"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">C</text></svg>`,
  'https://zhihu.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%230066ff"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">知</text></svg>`,
  'https://v2ex.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%231f1f1f"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%23f9a825" text-anchor="middle" font-family="system-ui">V</text></svg>`,
  'https://reddit.com/r/programming': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff4500"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">R</text></svg>`,
  'https://dev.to': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%230a0a0a"/><text x="16" y="22" font-size="12" font-weight="bold" fill="%23fff" text-anchor="middle" font-family="system-ui">dev</text></svg>`,
  'https://hashnode.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232962ff"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">H</text></svg>`,
  'https://medium.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%23fff" text-anchor="middle" font-family="system-ui">M</text></svg>`,

  // 学习资源
  'https://freecodecamp.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%230a0a0a"/><text x="16" y="22" font-size="10" font-weight="bold" fill="%230ff" text-anchor="middle" font-family="system-ui">FCC</text></svg>`,
  'https://leetcode.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ffa116"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">L</text></svg>`,
  'https://leetcode.cn': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23f97316"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">力</text></svg>`,
  'https://nowcoder.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%236c757d"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">牛</text></svg>`,
  'https://hackerrank.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2332c767"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">HR</text></svg>`,
  'https://codecademy.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232c49a4"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">CC</text></svg>`,
  'https://coursera.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%230056d2"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">C</text></svg>`,
  'https://imooc.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232d84c8"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">慕</text></svg>`,
  'https://bilibili.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2300a1d6"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">B</text></svg>`,
  'https://youtube.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23ff0000"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">YT</text></svg>`,

  // 技术参考
  'https://git-scm.com/doc': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23f05032"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">G</text></svg>`,
  'https://npmjs.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23cb3837"/><text x="16" y="22" font-size="12" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">npm</text></svg>`,
  'https://yarnpkg.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%232c8ebb"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">Y</text></svg>`,
  'https://pnpm.io': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23f692ce"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">p</text></svg>`,
  'https://maven.apache.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23c71a36"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">M</text></svg>`,
  'https://gradle.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2302303a"/><text x="16" y="22" font-size="14" font-weight="bold" fill="%236db5ec" text-anchor="middle" font-family="system-ui">G</text></svg>`,
  'https://redis.io': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23dc382d"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">R</text></svg>`,
  'https://mongodb.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%2347a248"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">M</text></svg>`,
  'https://postgresql.org': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%23336791"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">PG</text></svg>`,
  'https://mysql.com': `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="%234479a1"/><text x="16" y="22" font-size="14" font-weight="bold" fill="white" text-anchor="middle" font-family="system-ui">My</text></svg>`,
};

// 获取本地 favicon URL
function getLocalFavicon(url) {
  return FAVICON_MAP[url] || null;
}

// 暴露到全局
window.LinkHubFavicons = {
  getLocalFavicon,
  FAVICON_MAP
};
